services:
  - type: web
    name: rikos-api
    runtime: node
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: "20"
