services:
  - type: web
    name: rikos-api
    runtime: node
    rootDir: server
    startCommand: node index.js
    buildCommand: npm install
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: "20"
