export { Dashboard } from './dashboard.jsx'
export { StockPage } from './stock.jsx'
export { ShiftsPage } from './shifts.jsx'
export { ProductsPage } from './products.jsx'
export { SoportePage } from './support.jsx'
