export { Dashboard } from './dashboard.jsx'
export { StockPage } from './stock.jsx'
export { ShiftsPage } from './shifts.jsx'
export { ProductsPage } from './products.jsx'
export { ProductDetailPage } from './product-detail-page.jsx'
export { SoportePage } from './support.jsx'
export { SuppliersPage } from './suppliers.jsx'
